config/urls.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.conf import settings
from django.contrib import admin
from django.contrib.admindocs import urls as admindocs_urls
from django.urls import include, path

from socnet.allauth import urls as allauth_urls
from socnet.api import urls as api_urls
from socnet.blog import urls as blog_urls
from socnet.core import urls as core_urls
from socnet.messenger import urls as messenger_urls
from socnet.users import urls as users_urls

if TYPE_CHECKING:
    from django.urls import URLPattern, URLResolver

urlpatterns: list[URLPattern | URLResolver] = [
    path(f"{settings.ADMIN_URL}/doc/", include(admindocs_urls)),
    path(f"{settings.ADMIN_URL}/", admin.site.urls),
    path("api/", include(api_urls)),
    path("messenger/", include(messenger_urls)),
    path("", include(allauth_urls)),
    path("", include(core_urls)),
    path("", include(blog_urls)),
    path("", include(users_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

    if "debug_toolbar" in settings.INSTALLED_APPS:
        from debug_toolbar.toolbar import debug_toolbar_urls

        urlpatterns = [*debug_toolbar_urls(), *urlpatterns]

socnet/api/urls.py
from __future__ import annotations

from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

from . import viewsets

router = routers.SimpleRouter()
for prefix, viewset, basename in (
    ("comment-likes", viewsets.CommentLikeViewSet, "comment_likes"),
    ("post-likes", viewsets.PostLikeViewSet, "post_likes"),
    ("subscriptions", viewsets.SubscriptionViewSet, "subscriptions"),
    ("comments", viewsets.CommentViewSet, None),
    ("content-types", viewsets.ContentTypeViewSet, None),
    ("email-addresses", viewsets.EmailAddressViewSet, None),
    ("groups", viewsets.GroupViewSet, None),
    ("log-entries", viewsets.LogEntryViewSet, None),
    ("messages", viewsets.MessageViewSet, None),
    ("permissions", viewsets.PermissionViewSet, None),
    ("posts", viewsets.PostViewSet, None),
    ("users", viewsets.UserViewSet, None),
):
    router.register(prefix, viewset, basename)

urlpatterns = [
    *router.urls,
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"
    ),
]

socnet/blog/urls.py
from __future__ import annotations

from django.urls import include, path

from . import views

app_name = "blog"

post_patterns = [
    path("", views.posts_view, name="posts"),
    path("<int:pk>/", views.post_view, name="post"),
    path("create/", views.PostCreateView.as_view(), name="post_create"),
    path("<int:pk>/comments/", views.comments_view, name="comments"),
    path("<int:pk>/edit/", views.PostUpdateView.as_view(), name="post_update"),
    path("<int:pk>/delete/", views.post_delete_view, name="post_delete"),
]
comment_patterns = [
    path("edit/", views.CommentUpdateView.as_view(), name="comment_update"),
    path("delete/", views.comment_delete_view, name="comment_delete"),
]
user_patterns = [
    path("", views.user_view, name="user"),
    path("posts/", views.user_posts_view, name="user_posts"),
    path("liked/", views.liked_posts_view, name="liked_posts"),
    path("subscribers/", views.subscribers_view, name="subscribers"),
    path("subscriptions/", views.subscriptions_view, name="subscriptions"),
]
urlpatterns = [
    path("post/", include(post_patterns)),
    path("comment/<int:pk>/", include(comment_patterns)),
    path("@<slug:username>/", include(user_patterns)),
]

socnet/core/urls.py
from __future__ import annotations

from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path("favicon.ico", views.favicon_view, name="favicon"),
    path("manifest.json", views.ManifestView.as_view(), name="manifest"),
    path("", views.index_view, name="index"),
]

socnet/messenger/urls.py
from __future__ import annotations

from django.urls import path

from . import views

app_name = "messenger"
urlpatterns = [
    path("<slug:username>/", views.chat_view, name="chat"),
    path("", views.chats_view, name="chats"),
]

socnet/users/urls.py
from __future__ import annotations

from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("account/delete/", views.delete_account_view, name="delete_account"),
    path(
        "account/security/",
        views.AccountSecurityView.as_view(),
        name="account_security",
    ),
    path("profile/edit/", views.edit_profile_view, name="edit_profile"),
    path("users/search/", views.search_users_view, name="search_users"),
]

socnet/account/forms.py
from __future__ import annotations

from typing import Any

from allauth.account import forms as allauth_forms
from allauth_2fa import forms as allauth_2fa_forms
from django.utils.translation import gettext, gettext_lazy as _, pgettext_lazy

# Needed to redefine translation
pgettext_lazy("field label", "Login")
_("Password (again)")


class LoginForm(allauth_forms.LoginForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["login"].widget.attrs["placeholder"] = self.fields["login"].label


class AddEmailForm(allauth_forms.AddEmailForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["email"].label = ""
        del self.fields["email"].widget.attrs["placeholder"]


class ResetPasswordForm(allauth_forms.ResetPasswordForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["email"].label = ""
        del self.fields["email"].widget.attrs["placeholder"]


class SignupForm(allauth_forms.SignupForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        label = gettext("Email")
        self.fields["email"].label = label
        self.fields["email"].widget.attrs["placeholder"] = label


class TOTPDeviceForm(allauth_2fa_forms.TOTPDeviceForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["token"].label = ""

socnet/blog/views.py
from __future__ import annotations

from typing import TYPE_CHECKING, override

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.contrib.postgres.search import TrigramWordSimilarity
from django.core.exceptions import PermissionDenied
from django.db.models import Case, Count, Prefetch, Q, When
from django.db.models.functions import Extract
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _
from django.views.decorators.http import require_http_methods, require_POST
from django.views.generic import CreateView, UpdateView

from ..core.decorators import require_htmx, vary_on_htmx
from ..core.utils import paginate
from ..users.models import User
from . import forms, models, services

if TYPE_CHECKING:
    from typing import Any

    from django.db.models import QuerySet
    from typing_extensions import TypeVar

    from ..core.types import AuthedRequest, HttpRequest

    TBaseModelForm = TypeVar(
        "TBaseModelForm", bound=forms.PostForm | forms.CommentForm
    )
    TPost = TypeVar("TPost", bound=models.Post | models.Comment)


class _BasePostUpdateView(
    LoginRequiredMixin, UpdateView["TPost", "TBaseModelForm"]
):
    @override
    def get_object(self, queryset: QuerySet[TPost] | None = None) -> TPost:
        obj = super().get_object(queryset)
        if obj.author_id != self.request.user.pk:
            raise PermissionDenied
        return obj

    @override
    def form_valid(self, form: TBaseModelForm) -> HttpResponse:
        self.object = form.save(commit=False)  # type: ignore[assignment]
        update_fields = (
            (*form.Meta.fields, "date_updated")
            if form.content_has_changed
            else form.Meta.fields
        )
        self.object.save(update_fields=update_fields)
        form.save_m2m()
        return HttpResponseRedirect(self.get_success_url())


class PostUpdateView(_BasePostUpdateView[models.Post, forms.PostForm]):
    model = models.Post
    form_class = forms.PostForm
    template_name = "blog/post_update.html"

    @override
    def get_queryset(self) -> QuerySet[models.Post]:
        return (
            super()
            .get_queryset()
            .only("author_id", *self.form_class.Meta.fields)
        )


class CommentUpdateView(_BasePostUpdateView[models.Comment, forms.CommentForm]):
    model = models.Comment
    form_class = forms.CommentForm
    template_name = "blog/comment_update.html"

    @override
    def get_queryset(self) -> QuerySet[models.Comment]:
        return (
            super()
            .get_queryset()
            .only("author_id", "post_id", *self.form_class.Meta.fields)
        )


class PostCreateView(
    LoginRequiredMixin, CreateView[models.Post, forms.PostForm]
):
    form_class = forms.PostForm
    template_name = "blog/post_create.html"

    @override
    def form_valid(self, form: forms.PostForm) -> HttpResponse:
        form.instance.author = self.request.user  # type: ignore[assignment]
        return super().form_valid(form)


@require_http_methods({"DELETE"})
@login_required
def comment_delete_view(request: AuthedRequest, pk: int) -> HttpResponse:
    models.Comment.objects.filter(
        Q(author=request.user) | Q(post__author=request.user), pk=pk
    ).delete()
    return HttpResponse()


@require_POST
@login_required
def post_delete_view(request: AuthedRequest, pk: int) -> HttpResponse:
    models.Post.objects.filter(pk=pk, author=request.user).delete()
    return redirect("blog:user_posts", request.user.username)


def post_view(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method == "POST":
        if request.user.is_anonymous:
            return redirect_to_login(next=request.path)
        form = forms.CommentForm(request.POST)
        if (
            form.is_valid()
            and models.Post.objects.filter(
                Q(allow_commenting=True) | Q(author=request.user), pk=pk
            ).exists()
        ):
            form.instance.author = request.user
            form.instance.post_id = pk
            form.save()
            return redirect(request.path)
        messages.error(
            request,
            _(
                "An error occurred while creating the comment. Please try"
                " again."
            ),
        )
    else:
        form = forms.CommentForm()
    qs = services.get_posts_preview_qs(request, ("allow_commenting",)).filter(
        pk=pk
    )
    if "#comment" in request.path:
        comments_qs = (
            models.Comment.objects.only(
                "content",
                "post_id",
                "author__display_name",
                "author__image",
                "author__username",
            )
            .annotate_epoch_dates()
            .annotate(Count("likers"))
            .select_related("author")
            .order_by("pk")
        )
        if request.user.is_authenticated:
            comments_qs = comments_qs.annotate(
                is_liked=Q(pk__in=request.user.liked_comments.all())
            )
        qs = qs.prefetch_related(Prefetch("comments", comments_qs))
        post = get_object_or_404(qs)
        comments = post.comments.all()
    else:
        post = get_object_or_404(qs)
        comments = None
    context = {"post": post, "comments": comments, "form": form}
    return render(request, "blog/post.html", context)


@require_htmx
def comments_view(request: HttpRequest, pk: int) -> HttpResponse:
    comments_qs = (
        models.Comment.objects.only(
            "content",
            "post_id",
            "author__display_name",
            "author__image",
            "author__username",
        )
        .annotate_epoch_dates()
        .annotate(Count("likers"))
        .select_related("author")
        .filter(post_id=pk)
        .order_by("pk")
    )
    if request.user.is_authenticated:
        comments_qs = comments_qs.annotate(
            is_liked=Q(pk__in=request.user.liked_comments.all())
        )
    return render(
        request,
        "blog/inc/comments.html",
        {"comments": paginate(request, comments_qs, per_page=10)},
    )


@vary_on_htmx
def posts_view(request: HttpRequest) -> HttpResponse:
    posts: QuerySet[models.Post] | None = None
    qs = services.get_posts_preview_qs(request)
    is_search = bool(request.GET.get("q"))
    if is_search:
        form = forms.PostSearchForm(request.GET)
        if form.is_valid():
            q: str = form.cleaned_data["q"]
            posts = (
                qs.annotate(similarity=TrigramWordSimilarity(q, "content"))
                .filter(similarity__gte=0.6)
                .order_by("-pk")
            )
    else:
        form = forms.PostSearchForm()
        if request.user.is_authenticated:
            posts = qs.filter(
                author__in=request.user.subscriptions.all()
            ).order_by("-pk")
    context: dict[str, Any] = {
        "posts": paginate(request, posts, per_page=10) if posts else None
    }
    if request.htmx:
        template = "blog/inc/posts_preview.html"
    else:
        template = "blog/posts.html"
        context.update({"is_search": is_search, "form": form})
    return render(request, template, context)


@vary_on_htmx
def liked_posts_view(request: HttpRequest, username: str) -> HttpResponse:
    if request.htmx:
        qs = User.objects.only("pk")
        template = "blog/inc/posts_preview.html"
    else:
        qs = User.objects.only("display_name", "username")
        template = "blog/liked_posts.html"
    user = get_object_or_404(qs.filter(username=username))
    posts = paginate(
        request,
        services.get_posts_preview_qs(request)
        .filter(likers=user)
        .order_by("-pk"),
        per_page=10,
    )
    context = {"posts": posts, "user": user}
    return render(request, template, context)


@vary_on_htmx
def user_posts_view(request: HttpRequest, username: str) -> HttpResponse:
    posts = (
        models.Post.objects.only("allow_commenting", "author_id", "content")
        .annotate_epoch_dates()
        .annotate(
            Count("comments", distinct=True), Count("likers", distinct=True)
        )
        .order_by("-pk")
    )
    prefetch = Prefetch(
        "posts",
        (
            posts.annotate(is_liked=Q(pk__in=request.user.liked_posts.all()))
            if request.user.is_authenticated
            else posts
        ),
    )
    qs = (
        User.objects.only("display_name", "image", "username")
        .prefetch_related(prefetch)
        .filter(username=username)
    )
    user = get_object_or_404(qs)
    context: dict[str, Any] = {}
    if request.htmx:
        template = "blog/inc/posts_preview.html"
    else:
        template = "blog/user_posts.html"
        context["user"] = user
    context["posts"] = paginate(request, user.posts.all(), per_page=10)
    return render(request, template, context)


def subscribers_view(request: HttpRequest, username: str) -> HttpResponse:
    user = services.get_subscriptions(username, "subscribers")
    context = {"user": user, "subscribers": user.subscribers.all()}
    return render(request, "blog/subscribers.html", context)


def subscriptions_view(request: HttpRequest, username: str) -> HttpResponse:
    user = services.get_subscriptions(username, "subscriptions")
    context = {"user": user, "subscriptions": user.subscriptions.all()}
    return render(request, "blog/subscriptions.html", context)


def user_view(request: HttpRequest, username: str) -> HttpResponse:
    qs = (
        User.objects.only(
            "about",
            "birth_date",
            "display_name",
            "image",
            "location",
            "username",
        )
        .annotate(

socnet/core/views.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.templatetags.static import static
from django.views.generic import TemplateView

if TYPE_CHECKING:
    from django.http import HttpResponse

    from ..core.types import HttpRequest
    from .types import AuthedRequest


@login_required
def index_view(request: AuthedRequest) -> HttpResponse:
    return redirect(request.user)


def favicon_view(request: HttpRequest) -> HttpResponse:  # noqa: ARG001
    return redirect(static("img/favicon.ico"))


class ManifestView(TemplateView):
    template_name = "site.webmanifest"
    content_type = "application/json"

socnet/templates/403_csrf.html
{% extends "card.html" %}

{% load i18n %}

{% block title %}
  {% translate "CSRF verification failed (403)" %}
{% endblock title %}
{% block card %}
  <h3 class="mb-0 text-center">
    {% translate "CSRF verification failed (403)" %}
  </h3>
{% endblock card %}

socnet/templates/429.html
{% extends "card.html" %}

{% load i18n %}

{% block title %}
  {% translate "Too Many Requests (429)" %}
{% endblock title %}
{% block card %}
  <h3 class="mb-0 text-center">{% translate "Too Many Requests (429)" %}</h3>
{% endblock card %}

socnet/templates/base.html
{% load i18n static django_htmx %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}" data-bs-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
      {% endblock title %}
    | SocNet</title>
    {% include "inc/favicon.html" %}
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5/dist/css/bootstrap.min.css"
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/bootstrap_overrides.css' %}" />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6/css/all.min.css"
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    {% block css %}
    {% endblock css %}
    <script type="module"
            src="https://cdn.jsdelivr.net/npm/bootstrap@5/+esm"
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
    <script type="module"
            src="https://cdn.jsdelivr.net/npm/htmx.org@2/+esm"
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
    {% django_htmx_script %}
    <script type="module" src="{% static 'js/theme.js' %}"></script>
    <script type="module" src="{% static 'js/trim_input.js' %}"></script>
    {% block javascript %}
    {% endblock javascript %}
  </head>
  <body hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'>
    <div class="mb-3 sticky-top">
      <nav class="navbar navbar-expand-xl bg-body border-bottom">
        <div class="container-xxl">
          <a href="{% url 'core:index' %}"
             class="navbar-brand text-bg-primary rounded px-2 py-1"><i class="fa-solid fa-s"></i> <i class="fa-solid fa-o"></i> <i class="fa-solid fa-c"></i> <i class="fa-solid fa-n"></i> <i class="fa-solid fa-e"></i> <i class="fa-solid fa-t"></i></a>
          <button type="button"
                  class="navbar-toggler"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  {% with user_url=request.user.get_absolute_url %}
                    <a href="{{ user_url }}"
                       class="nav-link{% if user_url == request.path %} active{% endif %}"><i class="fa-solid fa-user text-primary"></i> {% translate "My profile" %}</a>
                  {% endwith %}
                </li>
                <li class="nav-item">
                  {% url "blog:posts" as url_posts %}
                  <a href="{{ url_posts }}"
                     class="nav-link{% if url_posts == request.path %} active{% endif %}"><i class="fa-solid fa-newspaper text-primary"></i> {% translate "Posts" %}</a>
                </li>
                <li class="nav-item">
                  {% url "messenger:chats" as url_chats %}
                  <a href="{{ url_chats }}"
                     class="nav-link{% if url_chats == request.path %} active{% endif %}"><i class="fa-solid fa-message text-primary"></i> {% translate "Messenger" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  {% url "blog:posts" as url_posts %}
                  <a href="{{ url_posts }}"
                     class="nav-link{% if url_posts == request.path %} active{% endif %}"><i class="fa-solid fa-newspaper text-primary"></i> {% translate "Posts" %}</a>
                </li>
              {% endif %}
              <li class="nav-item">
                {% url "users:search_users" as url_search_users %}
                <a href="{{ url_search_users }}"
                   class="nav-link{% if url_search_users == request.path %} active{% endif %}"><i class="fa-solid fa-magnifying-glass text-primary"></i> {% blocktranslate context "noun" %}Search users{% endblocktranslate %}</a>
              </li>
              {% if request.user.is_staff %}
                <li class="nav-item">
                  <a href="{% url 'admin:index' %}" class="nav-link"><i class="fa-solid fa-toolbox text-primary"></i> {% translate "Admin panel" %}</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'swagger-ui' %}" class="nav-link"><i class="fa-solid fa-bolt text-primary"></i> API</a>
                </li>
              {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto">
              <li class="nav-item dropdown">
                {% if request.user.is_authenticated %}
                  <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"><i class="fa-solid fa-gear text-primary"></i></a>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                      {% url "users:account_security" as url_account_security %}
                      {% if url_account_security == request.path %}
                        <a href="{{ url_account_security }}" class="dropdown-item active"><i class="fa-solid fa-shield"></i> {% translate "Security" %}</a>
                      {% else %}
                        <a href="{{ url_account_security }}" class="dropdown-item"><i class="fa-solid fa-shield text-primary"></i> {% translate "Security" %}</a>
                      {% endif %}
                    </li>
                    <li>
                      {% url "account_logout" as url_account_logout %}
                      {% if url_account_logout == request.path %}
                        <a href="{{ url_account_logout }}" class="dropdown-item active"><i class="fa-solid fa-right-from-bracket"></i> {% blocktranslate context "noun" %}Log out{% endblocktranslate %}</a>
                      {% else %}
                        <a href="{{ url_account_logout }}" class="dropdown-item"><i class="fa-solid fa-right-from-bracket text-primary"></i> {% blocktranslate context "noun" %}Log out{% endblocktranslate %}</a>
                      {% endif %}
                    </li>
                  </ul>
                {% else %}
                  <li class="nav-item">
                    {% url "account_login" as url_login %}
                    <a href="{{ url_login }}"
                       class="nav-link{% if url_login == request.path %} active{% endif %}"><i class="fa-solid fa-user text-primary"></i> {% blocktranslate context "noun" %}Log in{% endblocktranslate %}</a>
                  </li>
                  <li class="nav-item">
                    {% url "account_signup" as url_signup %}
                    <a href="{{ url_signup }}"
                       class="nav-link{% if url_signup == request.path %} active{% endif %}"><i class="fa-solid fa-clipboard-list text-primary"></i> {% translate "Sign-up" %}</a>
                  </li>
                {% endif %}
              </li>
              <li id="themeSwitcher" class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"><i id="currentThemeIcon" class="fa-solid fa-moon text-primary"></i></a>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li>
                    <button type="button" class="dropdown-item" data-bs-theme-value="light">
                      <i class="fa-solid fa-sun text-primary"></i>
                      {% translate "Light" %}
                    </button>
                  </li>
                  <li>
                    <button type="button" class="dropdown-item active" data-bs-theme-value="dark">
                      <i class="fa-solid fa-moon"></i>
                      {% translate "Dark" %}
                    </button>
                  </li>
                  <li>
                    <button type="button" class="dropdown-item" data-bs-theme-value="auto">
                      <i class="fa-solid fa-circle-half-stroke text-primary"></i>
                      {% translate "Auto" %}
                    </button>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="container-xxl">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags|default:'primary' }} alert-dismissible fade show"
             role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
      {% endfor %}
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

socnet/templates/card.html
{% extends "col.html" %}

{% block col %}
  <div class="card">
    <div class="card-body">
      {% block card %}
      {% endblock card %}
    </div>
  </div>
{% endblock col %}

socnet/templates/col.html
{% extends "base.html" %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-xl-6">
      {% block col %}
      {% endblock col %}
    </div>
  </div>
{% endblock content %}

socnet/templates/list_group.html
{% extends "col.html" %}

{% block col %}
  <div class="list-group">
    {% block list_group %}
    {% endblock list_group %}
  </div>
{% endblock col %}