config/urls.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.conf import settings
from django.contrib import admin
from django.contrib.admindocs import urls as admindocs_urls
from django.urls import include, path

from socnet.allauth import urls as allauth_urls
from socnet.api import urls as api_urls
from socnet.blog import urls as blog_urls
from socnet.core import urls as core_urls
from socnet.messenger import urls as messenger_urls
from socnet.users import urls as users_urls

if TYPE_CHECKING:
    from django.urls import URLPattern, URLResolver

urlpatterns: list[URLPattern | URLResolver] = [
    path(f"{settings.ADMIN_URL}/doc/", include(admindocs_urls)),
    path(f"{settings.ADMIN_URL}/", admin.site.urls),
    path("api/", include(api_urls)),
    path("messenger/", include(messenger_urls)),
    path("", include(allauth_urls)),
    path("", include(core_urls)),
    path("", include(blog_urls)),
    path("", include(users_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

    if "debug_toolbar" in settings.INSTALLED_APPS:
        from debug_toolbar.toolbar import debug_toolbar_urls

        urlpatterns = [*debug_toolbar_urls(), *urlpatterns]

socnet/api/urls.py
from __future__ import annotations

from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

from . import viewsets

router = routers.SimpleRouter()
for prefix, viewset, basename in (
    ("comment-likes", viewsets.CommentLikeViewSet, "comment_likes"),
    ("post-likes", viewsets.PostLikeViewSet, "post_likes"),
    ("subscriptions", viewsets.SubscriptionViewSet, "subscriptions"),
    ("comments", viewsets.CommentViewSet, None),
    ("content-types", viewsets.ContentTypeViewSet, None),
    ("email-addresses", viewsets.EmailAddressViewSet, None),
    ("groups", viewsets.GroupViewSet, None),
    ("log-entries", viewsets.LogEntryViewSet, None),
    ("messages", viewsets.MessageViewSet, None),
    ("permissions", viewsets.PermissionViewSet, None),
    ("posts", viewsets.PostViewSet, None),
    ("users", viewsets.UserViewSet, None),
):
    router.register(prefix, viewset, basename)

urlpatterns = [
    *router.urls,
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"
    ),
]

socnet/blog/urls.py
from __future__ import annotations

from django.urls import include, path

from . import views

app_name = "blog"

post_patterns = [
    path("", views.posts_view, name="posts"),
    path("<int:pk>/", views.post_view, name="post"),
    path("create/", views.PostCreateView.as_view(), name="post_create"),
    path("<int:pk>/comments/", views.comments_view, name="comments"),
    path("<int:pk>/edit/", views.PostUpdateView.as_view(), name="post_update"),
    path("<int:pk>/delete/", views.post_delete_view, name="post_delete"),
]
comment_patterns = [
    path("edit/", views.CommentUpdateView.as_view(), name="comment_update"),
    path("delete/", views.comment_delete_view, name="comment_delete"),
]
user_patterns = [
    path("", views.user_view, name="user"),
    path("posts/", views.user_posts_view, name="user_posts"),
    path("liked/", views.liked_posts_view, name="liked_posts"),
    path("subscribers/", views.subscribers_view, name="subscribers"),
    path("subscriptions/", views.subscriptions_view, name="subscriptions"),
]
urlpatterns = [
    path("post/", include(post_patterns)),
    path("comment/<int:pk>/", include(comment_patterns)),
    path("@<slug:username>/", include(user_patterns)),
]

socnet/core/urls.py
from __future__ import annotations

from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path("favicon.ico", views.favicon_view, name="favicon"),
    path("manifest.json", views.ManifestView.as_view(), name="manifest"),
    path("", views.index_view, name="index"),
]

socnet/blog/views.py
from __future__ import annotations

from typing import TYPE_CHECKING, override

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.contrib.postgres.search import TrigramWordSimilarity
from django.core.exceptions import PermissionDenied
from django.db.models import Case, Count, Prefetch, Q, When
from django.db.models.functions import Extract
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _
from django.views.decorators.http import require_http_methods, require_POST
from django.views.generic import CreateView, UpdateView

from ..core.decorators import require_htmx, vary_on_htmx
from ..core.utils import paginate
from ..users.models import User
from . import forms, models, services

if TYPE_CHECKING:
    from typing import Any

    from django.db.models import QuerySet
    from typing_extensions import TypeVar

    from ..core.types import AuthedRequest, HttpRequest

    TBaseModelForm = TypeVar(
        "TBaseModelForm", bound=forms.PostForm | forms.CommentForm
    )
    TPost = TypeVar("TPost", bound=models.Post | models.Comment)


class _BasePostUpdateView(
    LoginRequiredMixin, UpdateView["TPost", "TBaseModelForm"]
):
    @override
    def get_object(self, queryset: QuerySet[TPost] | None = None) -> TPost:
        obj = super().get_object(queryset)
        if obj.author_id != self.request.user.pk:
            raise PermissionDenied
        return obj

    @override
    def form_valid(self, form: TBaseModelForm) -> HttpResponse:
        self.object = form.save(commit=False)  # type: ignore[assignment]
        update_fields = (
            (*form.Meta.fields, "date_updated")
            if form.content_has_changed
            else form.Meta.fields
        )
        self.object.save(update_fields=update_fields)
        form.save_m2m()
        return HttpResponseRedirect(self.get_success_url())


class PostUpdateView(_BasePostUpdateView[models.Post, forms.PostForm]):
    model = models.Post
    form_class = forms.PostForm
    template_name = "blog/post_update.html"

    @override
    def get_queryset(self) -> QuerySet[models.Post]:
        return (
            super()
            .get_queryset()
            .only("author_id", *self.form_class.Meta.fields)
        )


class CommentUpdateView(_BasePostUpdateView[models.Comment, forms.CommentForm]):
    model = models.Comment
    form_class = forms.CommentForm
    template_name = "blog/comment_update.html"

    @override
    def get_queryset(self) -> QuerySet[models.Comment]:
        return (
            super()
            .get_queryset()
            .only("author_id", "post_id", *self.form_class.Meta.fields)
        )


class PostCreateView(
    LoginRequiredMixin, CreateView[models.Post, forms.PostForm]
):
    form_class = forms.PostForm
    template_name = "blog/post_create.html"

    @override
    def form_valid(self, form: forms.PostForm) -> HttpResponse:
        form.instance.author = self.request.user  # type: ignore[assignment]
        return super().form_valid(form)


@require_http_methods({"DELETE"})
@login_required
def comment_delete_view(request: AuthedRequest, pk: int) -> HttpResponse:
    models.Comment.objects.filter(
        Q(author=request.user) | Q(post__author=request.user), pk=pk
    ).delete()
    return HttpResponse()


@require_POST
@login_required
def post_delete_view(request: AuthedRequest, pk: int) -> HttpResponse:
    models.Post.objects.filter(pk=pk, author=request.user).delete()
    return redirect("blog:user_posts", request.user.username)


def post_view(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method == "POST":
        if request.user.is_anonymous:
            return redirect_to_login(next=request.path)
        form = forms.CommentForm(request.POST)
        if (
            form.is_valid()
            and models.Post.objects.filter(
                Q(allow_commenting=True) | Q(author=request.user), pk=pk
            ).exists()
        ):
            form.instance.author = request.user
            form.instance.post_id = pk
            form.save()
            return redirect(request.path)
        messages.error(
            request,
            _(
                "An error occurred while creating the comment. Please try"
                " again."
            ),
        )
    else:
        form = forms.CommentForm()
    qs = services.get_posts_preview_qs(request, ("allow_commenting",)).filter(
        pk=pk
    )
    if "#comment" in request.path:
        comments_qs = (
            models.Comment.objects.only(
                "content",
                "post_id",
                "author__display_name",
                "author__image",
                "author__username",
            )
            .annotate_epoch_dates()
            .annotate(Count("likers"))
            .select_related("author")
            .order_by("pk")
        )
        if request.user.is_authenticated:
            comments_qs = comments_qs.annotate(
                is_liked=Q(pk__in=request.user.liked_comments.all())
            )
        qs = qs.prefetch_related(Prefetch("comments", comments_qs))
        post = get_object_or_404(qs)
        comments = post.comments.all()
    else:
        post = get_object_or_404(qs)
        comments = None
    context = {"post": post, "comments": comments, "form": form}
    return render(request, "blog/post.html", context)


@require_htmx
def comments_view(request: HttpRequest, pk: int) -> HttpResponse:
    comments_qs = (
        models.Comment.objects.only(
            "content",
            "post_id",
            "author__display_name",
            "author__image",
            "author__username",
        )
        .annotate_epoch_dates()
        .annotate(Count("likers"))
        .select_related("author")
        .filter(post_id=pk)
        .order_by("pk")
    )
    if request.user.is_authenticated:
        comments_qs = comments_qs.annotate(
            is_liked=Q(pk__in=request.user.liked_comments.all())
        )
    return render(
        request,
        "blog/inc/comments.html",
        {"comments": paginate(request, comments_qs, per_page=10)},
    )


@vary_on_htmx
def posts_view(request: HttpRequest) -> HttpResponse:
    posts: QuerySet[models.Post] | None = None
    qs = services.get_posts_preview_qs(request)
    is_search = bool(request.GET.get("q"))
    if is_search:
        form = forms.PostSearchForm(request.GET)
        if form.is_valid():
            q: str = form.cleaned_data["q"]
            posts = (
                qs.annotate(similarity=TrigramWordSimilarity(q, "content"))
                .filter(similarity__gte=0.6)
                .order_by("-pk")
            )
    else:
        form = forms.PostSearchForm()
        if request.user.is_authenticated:
            posts = qs.filter(
                author__in=request.user.subscriptions.all()
            ).order_by("-pk")
    context: dict[str, Any] = {
        "posts": paginate(request, posts, per_page=10) if posts else None
    }
    if request.htmx:
        template = "blog/inc/posts_preview.html"
    else:
        template = "blog/posts.html"
        context.update({"is_search": is_search, "form": form})
    return render(request, template, context)


@vary_on_htmx
def liked_posts_view(request: HttpRequest, username: str) -> HttpResponse:
    if request.htmx:
        qs = User.objects.only("pk")
        template = "blog/inc/posts_preview.html"
    else:
        qs = User.objects.only("display_name", "username")
        template = "blog/liked_posts.html"
    user = get_object_or_404(qs.filter(username=username))
    posts = paginate(
        request,
        services.get_posts_preview_qs(request)
        .filter(likers=user)
        .order_by("-pk"),
        per_page=10,
    )
    context = {"posts": posts, "user": user}
    return render(request, template, context)


@vary_on_htmx
def user_posts_view(request: HttpRequest, username: str) -> HttpResponse:
    posts = (
        models.Post.objects.only("allow_commenting", "author_id", "content")
        .annotate_epoch_dates()
        .annotate(
            Count("comments", distinct=True), Count("likers", distinct=True)
        )
        .order_by("-pk")
    )
    prefetch = Prefetch(
        "posts",
        (
            posts.annotate(is_liked=Q(pk__in=request.user.liked_posts.all()))
            if request.user.is_authenticated
            else posts
        ),
    )
    qs = (
        User.objects.only("display_name", "image", "username")
        .prefetch_related(prefetch)
        .filter(username=username)
    )
    user = get_object_or_404(qs)
    context: dict[str, Any] = {}
    if request.htmx:
        template = "blog/inc/posts_preview.html"
    else:
        template = "blog/user_posts.html"
        context["user"] = user
    context["posts"] = paginate(request, user.posts.all(), per_page=10)
    return render(request, template, context)


def subscribers_view(request: HttpRequest, username: str) -> HttpResponse:
    user = services.get_subscriptions(username, "subscribers")
    context = {"user": user, "subscribers": user.subscribers.all()}
    return render(request, "blog/subscribers.html", context)


def subscriptions_view(request: HttpRequest, username: str) -> HttpResponse:
    user = services.get_subscriptions(username, "subscriptions")
    context = {"user": user, "subscriptions": user.subscriptions.all()}
    return render(request, "blog/subscriptions.html", context)


def user_view(request: HttpRequest, username: str) -> HttpResponse:
    qs = (
        User.objects.only(
            "about",
            "birth_date",
            "display_name",
            "image",
            "location",
            "username",
        )
        .annotate(

socnet/core/views.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.templatetags.static import static
from django.views.generic import TemplateView

if TYPE_CHECKING:
    from django.http import HttpResponse

    from ..core.types import HttpRequest
    from .types import AuthedRequest


@login_required
def index_view(request: AuthedRequest) -> HttpResponse:
    return redirect(request.user)


def favicon_view(request: HttpRequest) -> HttpResponse:  # noqa: ARG001
    return redirect(static("img/favicon.ico"))


class ManifestView(TemplateView):
    template_name = "site.webmanifest"
    content_type = "application/json"

socnet/users/views.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import TrigramWordSimilarity
from django.db.models import Func, Value
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from ..core.decorators import vary_on_htmx
from ..core.utils import paginate
from . import forms
from .models import User

if TYPE_CHECKING:
    from typing import Any

    from django.http import HttpResponse

    from ..core.types import AuthedRequest, HttpRequest


@login_required
def delete_account_view(request: AuthedRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.AccountDeletionForm(request.user, request.POST)
        if form.is_valid():
            request.user.delete()
            return redirect(settings.LOGIN_URL)
    else:
        form = forms.AccountDeletionForm(request.user)
    context = {"form": form}
    return render(request, "users/delete_account.html", context)


class AccountSecurityView(LoginRequiredMixin, TemplateView):
    template_name = "users/account_security.html"


@login_required
def edit_profile_view(request: AuthedRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.EditProfileForm(
            request.POST, request.FILES, instance=request.user
        )
        if form.is_valid():
            form.save()
            return redirect(request.user)
    else:
        form = forms.EditProfileForm(instance=request.user)
    context = {"form": form}
    return render(request, "users/edit_profile.html", context)


@vary_on_htmx
def search_users_view(request: HttpRequest) -> HttpResponse:
    users = None
    if request.GET:
        form = forms.UserSearchForm(request.GET)
        if form.is_valid():
            query: str = form.cleaned_data["q"]
            search_fields: list[str] = form.cleaned_data["search_fields"]
            expr = Func(Value(" "), *search_fields, function="CONCAT_WS")
            similarity = TrigramWordSimilarity(query, expr)
            users = (
                User.objects.only("display_name", "image", "username")
                .annotate(similarity=similarity)
                .filter(similarity__gte=0.6)
                .order_by("-similarity")
            )
    else:
        form = forms.UserSearchForm()
    context: dict[str, Any] = {
        "users": paginate(request, users, per_page=10)
        if users is not None
        else None
    }
    if request.htmx:
        template_name = "users/inc/search_users.html"
    else:
        template_name = "users/search_users.html"
        context["form"] = form
    return render(request, template_name, context)

socnet/templates/blog/inc/comments.html
{% load i18n markdownify obj_admin_url %}

{% for comment in comments %}
  <div id="comment{{ comment.pk }}"
       class="list-group-item"
       {% if forloop.last and comments.has_next %} hx-get="{% querystring page=comments.next_page_number %}" hx-trigger="revealed" hx-swap="afterend" {% endif %}>
    <div class="d-flex justify-content-between mb-1">
      <a href="{{ comment.author.get_absolute_url }}"
         class="link-underline link-underline-opacity-0 link-underline-opacity-100-hover">
        <div class="d-flex">
          <div class="avatar-thumbnail me-2">
            {% if comment.author.image %}
              <img src="{{ comment.author.image.url }}" loading="lazy" class="rounded" />
            {% else %}
              <i class="fa-solid fa-user text-secondary"></i>
            {% endif %}
          </div>
          <div class="text-break">
            {{ comment.author.display_name }}
            <span class="text-secondary">@{{ comment.author.username }}</span>
          </div>
        </div>
      </a>
      {% if request.user.is_staff or request.user == comment.author or request.user == comment.post.author %}
        <div>
          <div class="dropdown">
            <button class="btn" type="button" data-bs-toggle="dropdown">
              <i class="fa-solid fa-ellipsis text-secondary"></i>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              {% if request.user.is_staff %}
                <li>
                  <a href="{{ comment|obj_admin_url }}" class="dropdown-item"><i class="fa-solid fa-toolbox text-primary"></i> {% translate "Admin page" %}</a>
                </li>
              {% endif %}
              {% if request.user == comment.author %}
                <li>
                  <a href="{% url 'blog:comment_update' comment.pk %}"
                     class="dropdown-item"><i class="fa-solid fa-pen-to-square text-primary"></i> {% translate "Edit" %}</a>
                </li>
              {% endif %}
              {% if request.user == comment.author or request.user == comment.post.author %}
                <li>
                  <button type="button"
                          data-bs-toggle="modal"
                          data-bs-target="#comment{{ comment.pk }}Modal"
                          class="dropdown-item">
                    <i class="fa-solid fa-xmark text-danger"></i>
                    {% translate "Delete" %}
                  </button>
                </li>
              {% endif %}
            </ul>
          </div>
          {% if request.user == comment.author or request.user == comment.post.author %}
            <div class="modal fade" id="comment{{ comment.pk }}Modal" tabindex="-1">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">
                      {% blocktranslate context "noun" %}Delete comment{% endblocktranslate %}
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                  </div>
                  <div class="modal-body"></div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                      {% translate "Close" %}
                    </button>
                    <button type="button"
                            data-bs-dismiss="modal"
                            hx-delete="{% url "blog:comment_delete" comment.pk %}"
                            hx-target="#comment{{ comment.pk }}"
                            hx-swap="delete"
                            class="btn btn-danger">
                      {% translate "Delete" %}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          {% endif %}
        </div>
      {% endif %}
    </div>
    <div class="markdown-container text-break">
      {{ comment.content|markdownify }}
    </div>
    <div class="d-flex justify-content-between align-items-center">
      {% include "blog/inc/timestamp.html" with object=comment %}
      {% if request.user.is_anonymous %}
        <a href="{% url 'account_login' %}?next={{ request.path|urlencode }}"
           class="btn badge rounded-pill text-bg-color fs-6"><i class="fa-regular fa-heart"></i> <span data-unformatted-number="{{ comment.likers__count }}"></span></a>
      {% elif comment.is_liked %}
        <button type="button"
                class="btn badge rounded-pill text-bg-color fs-6"
                data-is-liked="y"
                data-comment-pk="{{ comment.pk }}">
          <i class="fa-solid fa-heart text-danger"></i>
          <span data-unformatted-number="{{ comment.likers__count }}"></span>
        </button>
      {% else %}
        <button type="button"
                class="btn badge rounded-pill text-bg-color fs-6"
                data-is-liked="n"
                data-comment-pk="{{ comment.pk }}">
          <i class="fa-regular fa-heart"></i>
          <span data-unformatted-number="{{ comment.likers__count }}"></span>
        </button>
      {% endif %}
    </div>
  </div>
{% endfor %}

socnet/templates/blog/inc/post_body.html
{% load i18n markdownify obj_admin_url %}

<div class="d-flex mb-1">
  <a href="{{ post.author.get_absolute_url }}"
     class="avatar-thumbnail d-flex align-items-center me-2">
    {% if post.author.image %}
      <img src="{{ post.author.image.url }}" loading="lazy" class="rounded" />
    {% else %}
      <i class="fa-solid fa-user text-secondary"></i>
    {% endif %}
  </a>
  <div>
    <div>
      <a href="{{ post.author.get_absolute_url }}"
         class="link-underline link-underline-opacity-0 link-underline-opacity-100-hover text-break">{{ post.author.display_name }} <span class="text-secondary">@{{ post.author.username }}</span></a>
    </div>
    {% include "blog/inc/timestamp.html" with object=post %}
  </div>
  {% if request.user.is_staff or request.user == post.author %}
    <div class="ms-auto">
      <div class="dropdown">
        <button class="btn" type="button" data-bs-toggle="dropdown">
          <i class="fa-solid fa-ellipsis text-secondary"></i>
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
          {% if request.user.is_staff %}
            <li>
              <a href="{{ post|obj_admin_url }}" class="dropdown-item"><i class="fa-solid fa-toolbox text-primary"></i> {% translate "Admin page" %}</a>
            </li>
          {% endif %}
          {% if request.user == post.author %}
            <li>
              <a href="{% url 'blog:post_update' post.pk %}" class="dropdown-item"><i class="fa-solid fa-pen-to-square text-primary"></i> {% translate "Edit" %}</a>
            </li>
            <li>
              <button type="button"
                      class="dropdown-item"
                      data-bs-toggle="modal"
                      data-bs-target="#post{{ post.pk }}Modal">
                <i class="fa-solid fa-xmark text-danger"></i>
                {% translate "Delete" %}
              </button>
            </li>
          {% endif %}
        </ul>
      </div>
      {% if request.user == post.author %}
        <div class="modal fade" id="post{{ post.pk }}Modal" tabindex="-1">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">
                  {% blocktranslate context "noun" %}Delete post{% endblocktranslate %}
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
              </div>
              <div class="modal-body">
                {% translate "Are you sure you want to delete your post?" %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                  {% translate "Close" %}
                </button>
                <form method="post" action="{% url 'blog:post_delete' post.pk %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger">{% translate "Delete" %}</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    </div>
  {% endif %}
</div>
<div class="markdown-container text-break">{{ post.content|markdownify }}</div>
{% if request.user.is_anonymous %}
  <a href="{% url 'account_login' %}?next={{ request.path|urlencode }}"
     class="btn badge rounded-pill text-bg-color fs-6"><i class="fa-regular fa-heart"></i> <span data-unformatted-number="{{ post.likers__count }}"></span></a>
{% elif post.is_liked %}
  <button type="button"
          class="btn badge rounded-pill text-bg-color fs-6"
          data-is-liked="y"
          data-post-pk="{{ post.pk }}">
    <i class="fa-solid fa-heart text-danger"></i>
    <span data-unformatted-number="{{ post.likers__count }}"></span>
  </button>
{% else %}
  <button type="button"
          class="btn badge rounded-pill text-bg-color fs-6"
          data-is-liked="n"
          data-post-pk="{{ post.pk }}">
    <i class="fa-regular fa-heart"></i>
    <span data-unformatted-number="{{ post.likers__count }}"></span>
  </button>
{% endif %}
<a href="{{ post.get_absolute_url }}"
   class="btn badge rounded-pill text-bg-color fs-6"><i class="fa-regular fa-comment{% if not post.allow_commenting %} text-danger{% endif %}"></i> <span data-unformatted-number="{{ post.comments__count }}"></span></a>

socnet/templates/blog/inc/post_css.html
{% load static %}

{% include "inc/viewerjs_css.html" %}
<link rel="stylesheet" href="{% static 'css/avatar_thumbnail.css' %}" />
<link rel="stylesheet" href="{% static 'css/markdown_container.css' %}" />

socnet/templates/blog/inc/post_js.html
{% load static %}

<script type="module" src="{% static 'js/number_formatter.js' %}"></script>
<script type="module" src="{% static 'js/date_formatter.js' %}"></script>
{% if request.user.is_authenticated %}
  <script type="module" src="{% static 'js/like.js' %}"></script>
{% endif %}
<script type="module" src="{% static 'js/viewer_markdown.js' %}"></script>

socnet/templates/blog/inc/posts.html
{% for post in posts %}
  <div class="card mb-2">
    <div class="card-body">
      <div class="card-title">
        <div class="row">
          <div class="avatar-thumbnail">
            {% if post.user.image %}
              <img src="{{ post.user.image.url }}" alt="" loading="lazy" class="rounded"/>
            {% endif %}
          </div>
          <div class="col ms-2">
            <div class="text-break">
              <a class="text-decoration-none" href="{{ post.user.get_absolute_url }}">
                {{ post.user.get_username }}
              </a>
            </div>
            <div>
              <a class="text-muted text-decoration-none"
                 href="{{ post.get_absolute_url }}">
                {{ post.date }}
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="text-break">{{ post.text|linebreaksbr }}</div>
      {% if post.image %}
        <div>
          <img class="img-responsive rounded"
               src="{{ post.image.url }}"
               alt=""
               loading="lazy"/>
        </div>
      {% endif %}
      <div class="fs-4">
        {% if request.user.is_anonymous %}
          <a role="button"
             class="btn badge rounded-pill bg-light text-dark"
             href="{% url 'account_login' %}?next={{ request.path|urlencode }}">
            <i class="fa-regular fa-heart"></i>
            <span>{{ post.likers__count }}</span>
          </a>
        {% elif request.user in post.likers.all %}
          <button type="button"
                  class="btn badge rounded-pill bg-light text-dark"
                  data-is-liked="y"
                  data-post-pk="{{ post.pk }}">
            <i class="text-danger fa-solid fa-heart"></i>
            <span>{{ post.likers.count }}</span>
          </button >
        {% else %}
          <button type="button"
                  class="btn badge rounded-pill bg-light text-dark"
                  data-is-liked="n"
                  data-post-pk="{{ post.pk }}">
            <i class="fa-regular fa-heart"></i>
            <span>{{ post.likers.count }}</span>
          </button>
        {% endif %}
        <a role="button"
           href="{{ post.get_absolute_url }}"
           class="btn badge rounded-pill bg-light text-dark">
          <i class="fa-regular fa-comment"></i>
          {{ post.comments__count }}
        </a>
      </div>
    </div>
  </div>
{% endfor %}

socnet/templates/blog/inc/posts_preview.html
{% for post in posts %}
  <div class="card mt-2"
       {% if forloop.last and posts.has_next %} hx-get="{% querystring page=posts.next_page_number %}" hx-trigger="revealed" hx-swap="afterend" {% endif %}>
    <div class="card-body">{% include "blog/inc/post_body.html" %}</div>
  </div>
{% endfor %}

socnet/templates/blog/inc/timestamp.html
{% load i18n %}

<a href="{{ object.get_absolute_url }}"
   class="text-secondary link-underline-secondary link-underline-opacity-0 link-underline-opacity-100-hover"><span data-epoch="{{ object.date_created_epoch }}"></span>
{% if object.date_updated_epoch %}
  ({% translate "last edited" %} <span data-epoch="{{ object.date_updated_epoch }}"></span>)
{% endif %}
</a>