config/urls.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.conf import settings
from django.contrib import admin
from django.contrib.admindocs import urls as admindocs_urls
from django.urls import include, path

from socnet.allauth import urls as allauth_urls
from socnet.api import urls as api_urls
from socnet.blog import urls as blog_urls
from socnet.core import urls as core_urls
from socnet.messenger import urls as messenger_urls
from socnet.users import urls as users_urls

if TYPE_CHECKING:
    from django.urls import URLPattern, URLResolver

urlpatterns: list[URLPattern | URLResolver] = [
    path(f"{settings.ADMIN_URL}/doc/", include(admindocs_urls)),
    path(f"{settings.ADMIN_URL}/", admin.site.urls),
    path("api/", include(api_urls)),
    path("messenger/", include(messenger_urls)),
    path("", include(allauth_urls)),
    path("", include(core_urls)),
    path("", include(blog_urls)),
    path("", include(users_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

    if "debug_toolbar" in settings.INSTALLED_APPS:
        from debug_toolbar.toolbar import debug_toolbar_urls

        urlpatterns = [*debug_toolbar_urls(), *urlpatterns]

socnet/api/urls.py
from __future__ import annotations

from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

from . import viewsets

router = routers.SimpleRouter()
for prefix, viewset, basename in (
    ("comment-likes", viewsets.CommentLikeViewSet, "comment_likes"),
    ("post-likes", viewsets.PostLikeViewSet, "post_likes"),
    ("subscriptions", viewsets.SubscriptionViewSet, "subscriptions"),
    ("comments", viewsets.CommentViewSet, None),
    ("content-types", viewsets.ContentTypeViewSet, None),
    ("email-addresses", viewsets.EmailAddressViewSet, None),
    ("groups", viewsets.GroupViewSet, None),
    ("log-entries", viewsets.LogEntryViewSet, None),
    ("messages", viewsets.MessageViewSet, None),
    ("permissions", viewsets.PermissionViewSet, None),
    ("posts", viewsets.PostViewSet, None),
    ("users", viewsets.UserViewSet, None),
):
    router.register(prefix, viewset, basename)

urlpatterns = [
    *router.urls,
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"
    ),
]

socnet/blog/urls.py
from __future__ import annotations

from django.urls import include, path

from . import views

app_name = "blog"

post_patterns = [
    path("", views.posts_view, name="posts"),
    path("<int:pk>/", views.post_view, name="post"),
    path("create/", views.PostCreateView.as_view(), name="post_create"),
    path("<int:pk>/comments/", views.comments_view, name="comments"),
    path("<int:pk>/edit/", views.PostUpdateView.as_view(), name="post_update"),
    path("<int:pk>/delete/", views.post_delete_view, name="post_delete"),
]
comment_patterns = [
    path("edit/", views.CommentUpdateView.as_view(), name="comment_update"),
    path("delete/", views.comment_delete_view, name="comment_delete"),
]
user_patterns = [
    path("", views.user_view, name="user"),
    path("posts/", views.user_posts_view, name="user_posts"),
    path("liked/", views.liked_posts_view, name="liked_posts"),
    path("subscribers/", views.subscribers_view, name="subscribers"),
    path("subscriptions/", views.subscriptions_view, name="subscriptions"),
]
urlpatterns = [
    path("post/", include(post_patterns)),
    path("comment/<int:pk>/", include(comment_patterns)),
    path("@<slug:username>/", include(user_patterns)),
]

socnet/core/urls.py
from __future__ import annotations

from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path("favicon.ico", views.favicon_view, name="favicon"),
    path("manifest.json", views.ManifestView.as_view(), name="manifest"),
    path("", views.index_view, name="index"),
]

socnet/messenger/urls.py
from __future__ import annotations

from django.urls import path

from . import views

app_name = "messenger"
urlpatterns = [
    path("<slug:username>/", views.chat_view, name="chat"),
    path("", views.chats_view, name="chats"),
]

socnet/account/forms.py
from __future__ import annotations

from typing import Any

from allauth.account import forms as allauth_forms
from allauth_2fa import forms as allauth_2fa_forms
from django.utils.translation import gettext, gettext_lazy as _, pgettext_lazy

# Needed to redefine translation
pgettext_lazy("field label", "Login")
_("Password (again)")


class LoginForm(allauth_forms.LoginForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["login"].widget.attrs["placeholder"] = self.fields["login"].label


class AddEmailForm(allauth_forms.AddEmailForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["email"].label = ""
        del self.fields["email"].widget.attrs["placeholder"]


class ResetPasswordForm(allauth_forms.ResetPasswordForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["email"].label = ""
        del self.fields["email"].widget.attrs["placeholder"]


class SignupForm(allauth_forms.SignupForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        label = gettext("Email")
        self.fields["email"].label = label
        self.fields["email"].widget.attrs["placeholder"] = label


class TOTPDeviceForm(allauth_2fa_forms.TOTPDeviceForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["token"].label = ""

socnet/main/forms.py
from __future__ import annotations

from typing import Type

from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from ..users.models import User as UserType
from . import models

User: Type[UserType] = get_user_model()


class PostsSearchForm(forms.Form):
    q = forms.Field(
        widget=forms.Textarea(
            {
                "rows": "1",
                "class": "form-control",
                "placeholder": _("Search posts"),
            }
        ),
        label=_("Search query"),
    )


class PostCommentCreationForm(forms.ModelForm[models.PostComment]):
    class Meta:
        model = models.PostComment
        fields = ("text", "image")


class PostCreationForm(forms.ModelForm[models.Post]):
    class Meta:
        model = models.Post
        fields = ("text", "image")

socnet/blog/views.py
from __future__ import annotations

from typing import TYPE_CHECKING, override

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.contrib.postgres.search import TrigramWordSimilarity
from django.core.exceptions import PermissionDenied
from django.db.models import Case, Count, Prefetch, Q, When
from django.db.models.functions import Extract
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _
from django.views.decorators.http import require_http_methods, require_POST
from django.views.generic import CreateView, UpdateView

from ..core.decorators import require_htmx, vary_on_htmx
from ..core.utils import paginate
from ..users.models import User
from . import forms, models, services

if TYPE_CHECKING:
    from typing import Any

    from django.db.models import QuerySet
    from typing_extensions import TypeVar

    from ..core.types import AuthedRequest, HttpRequest

    TBaseModelForm = TypeVar(
        "TBaseModelForm", bound=forms.PostForm | forms.CommentForm
    )
    TPost = TypeVar("TPost", bound=models.Post | models.Comment)


class _BasePostUpdateView(
    LoginRequiredMixin, UpdateView["TPost", "TBaseModelForm"]
):
    @override
    def get_object(self, queryset: QuerySet[TPost] | None = None) -> TPost:
        obj = super().get_object(queryset)
        if obj.author_id != self.request.user.pk:
            raise PermissionDenied
        return obj

    @override
    def form_valid(self, form: TBaseModelForm) -> HttpResponse:
        self.object = form.save(commit=False)  # type: ignore[assignment]
        update_fields = (
            (*form.Meta.fields, "date_updated")
            if form.content_has_changed
            else form.Meta.fields
        )
        self.object.save(update_fields=update_fields)
        form.save_m2m()
        return HttpResponseRedirect(self.get_success_url())


class PostUpdateView(_BasePostUpdateView[models.Post, forms.PostForm]):
    model = models.Post
    form_class = forms.PostForm
    template_name = "blog/post_update.html"

    @override
    def get_queryset(self) -> QuerySet[models.Post]:
        return (
            super()
            .get_queryset()
            .only("author_id", *self.form_class.Meta.fields)
        )


class CommentUpdateView(_BasePostUpdateView[models.Comment, forms.CommentForm]):
    model = models.Comment
    form_class = forms.CommentForm
    template_name = "blog/comment_update.html"

    @override
    def get_queryset(self) -> QuerySet[models.Comment]:
        return (
            super()
            .get_queryset()
            .only("author_id", "post_id", *self.form_class.Meta.fields)
        )


class PostCreateView(
    LoginRequiredMixin, CreateView[models.Post, forms.PostForm]
):
    form_class = forms.PostForm
    template_name = "blog/post_create.html"

    @override
    def form_valid(self, form: forms.PostForm) -> HttpResponse:
        form.instance.author = self.request.user  # type: ignore[assignment]
        return super().form_valid(form)


@require_http_methods({"DELETE"})
@login_required
def comment_delete_view(request: AuthedRequest, pk: int) -> HttpResponse:
    models.Comment.objects.filter(
        Q(author=request.user) | Q(post__author=request.user), pk=pk
    ).delete()
    return HttpResponse()


@require_POST
@login_required
def post_delete_view(request: AuthedRequest, pk: int) -> HttpResponse:
    models.Post.objects.filter(pk=pk, author=request.user).delete()
    return redirect("blog:user_posts", request.user.username)


def post_view(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method == "POST":
        if request.user.is_anonymous:
            return redirect_to_login(next=request.path)
        form = forms.CommentForm(request.POST)
        if (
            form.is_valid()
            and models.Post.objects.filter(
                Q(allow_commenting=True) | Q(author=request.user), pk=pk
            ).exists()
        ):
            form.instance.author = request.user
            form.instance.post_id = pk
            form.save()
            return redirect(request.path)
        messages.error(
            request,
            _(
                "An error occurred while creating the comment. Please try"
                " again."
            ),
        )
    else:
        form = forms.CommentForm()
    qs = services.get_posts_preview_qs(request, ("allow_commenting",)).filter(
        pk=pk
    )
    if "#comment" in request.path:
        comments_qs = (
            models.Comment.objects.only(
                "content",
                "post_id",
                "author__display_name",
                "author__image",
                "author__username",
            )
            .annotate_epoch_dates()
            .annotate(Count("likers"))
            .select_related("author")
            .order_by("pk")
        )
        if request.user.is_authenticated:
            comments_qs = comments_qs.annotate(
                is_liked=Q(pk__in=request.user.liked_comments.all())
            )
        qs = qs.prefetch_related(Prefetch("comments", comments_qs))
        post = get_object_or_404(qs)
        comments = post.comments.all()
    else:
        post = get_object_or_404(qs)
        comments = None
    context = {"post": post, "comments": comments, "form": form}
    return render(request, "blog/post.html", context)


@require_htmx
def comments_view(request: HttpRequest, pk: int) -> HttpResponse:
    comments_qs = (
        models.Comment.objects.only(
            "content",
            "post_id",
            "author__display_name",
            "author__image",
            "author__username",
        )
        .annotate_epoch_dates()
        .annotate(Count("likers"))
        .select_related("author")
        .filter(post_id=pk)
        .order_by("pk")
    )
    if request.user.is_authenticated:
        comments_qs = comments_qs.annotate(
            is_liked=Q(pk__in=request.user.liked_comments.all())
        )
    return render(
        request,
        "blog/inc/comments.html",
        {"comments": paginate(request, comments_qs, per_page=10)},
    )


@vary_on_htmx
def posts_view(request: HttpRequest) -> HttpResponse:
    posts: QuerySet[models.Post] | None = None
    qs = services.get_posts_preview_qs(request)
    is_search = bool(request.GET.get("q"))
    if is_search:
        form = forms.PostSearchForm(request.GET)
        if form.is_valid():
            q: str = form.cleaned_data["q"]
            posts = (
                qs.annotate(similarity=TrigramWordSimilarity(q, "content"))
                .filter(similarity__gte=0.6)
                .order_by("-pk")
            )
    else:
        form = forms.PostSearchForm()
        if request.user.is_authenticated:
            posts = qs.filter(
                author__in=request.user.subscriptions.all()
            ).order_by("-pk")
    context: dict[str, Any] = {
        "posts": paginate(request, posts, per_page=10) if posts else None
    }
    if request.htmx:
        template = "blog/inc/posts_preview.html"
    else:
        template = "blog/posts.html"
        context.update({"is_search": is_search, "form": form})
    return render(request, template, context)


@vary_on_htmx
def liked_posts_view(request: HttpRequest, username: str) -> HttpResponse:
    if request.htmx:
        qs = User.objects.only("pk")
        template = "blog/inc/posts_preview.html"
    else:
        qs = User.objects.only("display_name", "username")
        template = "blog/liked_posts.html"
    user = get_object_or_404(qs.filter(username=username))
    posts = paginate(
        request,
        services.get_posts_preview_qs(request)
        .filter(likers=user)
        .order_by("-pk"),
        per_page=10,
    )
    context = {"posts": posts, "user": user}
    return render(request, template, context)


@vary_on_htmx
def user_posts_view(request: HttpRequest, username: str) -> HttpResponse:
    posts = (
        models.Post.objects.only("allow_commenting", "author_id", "content")
        .annotate_epoch_dates()
        .annotate(
            Count("comments", distinct=True), Count("likers", distinct=True)
        )
        .order_by("-pk")
    )
    prefetch = Prefetch(
        "posts",
        (
            posts.annotate(is_liked=Q(pk__in=request.user.liked_posts.all()))
            if request.user.is_authenticated
            else posts
        ),
    )
    qs = (
        User.objects.only("display_name", "image", "username")
        .prefetch_related(prefetch)
        .filter(username=username)
    )
    user = get_object_or_404(qs)
    context: dict[str, Any] = {}
    if request.htmx:
        template = "blog/inc/posts_preview.html"
    else:
        template = "blog/user_posts.html"
        context["user"] = user
    context["posts"] = paginate(request, user.posts.all(), per_page=10)
    return render(request, template, context)


def subscribers_view(request: HttpRequest, username: str) -> HttpResponse:
    user = services.get_subscriptions(username, "subscribers")
    context = {"user": user, "subscribers": user.subscribers.all()}
    return render(request, "blog/subscribers.html", context)


def subscriptions_view(request: HttpRequest, username: str) -> HttpResponse:
    user = services.get_subscriptions(username, "subscriptions")
    context = {"user": user, "subscriptions": user.subscriptions.all()}
    return render(request, "blog/subscriptions.html", context)


def user_view(request: HttpRequest, username: str) -> HttpResponse:
    qs = (
        User.objects.only(
            "about",
            "birth_date",
            "display_name",
            "image",
            "location",
            "username",
        )
        .annotate(

socnet/core/views.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.templatetags.static import static
from django.views.generic import TemplateView

if TYPE_CHECKING:
    from django.http import HttpResponse

    from ..core.types import HttpRequest
    from .types import AuthedRequest


@login_required
def index_view(request: AuthedRequest) -> HttpResponse:
    return redirect(request.user)


def favicon_view(request: HttpRequest) -> HttpResponse:  # noqa: ARG001
    return redirect(static("img/favicon.ico"))


class ManifestView(TemplateView):
    template_name = "site.webmanifest"
    content_type = "application/json"

socnet/templates/messenger/chat.html
{% extends "list_group.html" %}

{% load i18n static django_bootstrap5 markdownify %}

{% block title %}
  {% blocktranslate with display_name=interlocutor.display_name username=interlocutor.username %}Chat with {{ display_name }} ({{ username }}){% endblocktranslate %}
{% endblock title %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/chat.css' %}" />
  <link rel="stylesheet" href="{% static 'css/avatar_thumbnail.css' %}" />
  <link rel="stylesheet" href="{% static 'css/markdown_container.css' %}" />
  {% include "inc/viewerjs_css.html" %}
{% endblock css %}
{% block javascript %}
  <script type="module" src="{% static 'js/chat.js' %}"></script>
  <script type="module" src="{% static 'js/date_formatter.js' %}"></script>
  <script type="module" src="{% static 'js/autosize.js' %}"></script>
  {% if messages_ %}
    <script type="module" src="{% static 'js/viewer_markdown.js' %}"></script>
  {% endif %}
  <script id="data" type="application/json">
    {
      "interlocutorPk": {{ interlocutor.pk }},
      "users": {
        {% if request.user != interlocutor %}
        "{{ interlocutor.username|lower }}": {
          "href": "{{ interlocutor.get_absolute_url }}",
          {% if interlocutor.image %}"image": "{{ interlocutor.image.url }}",{% endif %}
          "displayName": "{{ interlocutor.display_name }}",
          "isCurrentUser": false
        },
        {% endif %}
        "{{ request.user.username|lower }}": {
          "href": "{{ request.user.get_absolute_url }}",
          {% if request.user.image %}"image": "{{ request.user.image.url }}",{% endif %}
          "displayName": "{{ request.user.display_name }}",
          "isCurrentUser": true
        }
      }
    }
  </script>
{% endblock javascript %}
{% block list_group %}
  <a href="{{ interlocutor.get_absolute_url }}"
     class="list-group-item list-group-item-action">
    <div class="d-flex align-items-center justify-content-center">
      {% if interlocutor.image %}
        <div class="avatar-thumbnail-no-height me-2">
          <img src="{{ interlocutor.image.url }}" loading="lazy" class="rounded" />
        </div>
      {% endif %}
      <div class="text-body text-break">
        {{ interlocutor.display_name }}
        ({{ interlocutor.username }})
      </div>
    </div>
  </a>
  <div class="list-group-item p-0">
    <div id="chat-log" class="p-3 overflow-x-hidden overflow-y-scroll">
      {% for message in messages_ %}
        <div id="msg{{ message.pk }}" class="d-flex mb-1">
          <a href="{{ message.sender.get_absolute_url }}"
             class="avatar-thumbnail d-flex align-items-center me-2">
            {% if message.sender.image %}
              <img src="{{ message.sender.image.url }}" loading="lazy" class="rounded" />
            {% else %}
              <i class="fa-solid fa-user text-secondary"></i>
            {% endif %}
          </a>
          <div>
            <a href="{{ message.sender.get_absolute_url }}"
               class="link-underline link-underline-opacity-0 link-underline-opacity-100-hover text-break">{{ message.sender.display_name }} <span class="text-secondary">@{{ message.sender.username }}</span></a>
            <div class="text-secondary" data-epoch="{{ message.date_created_epoch }}">
            </div>
          </div>
        </div>
        <div class="markdown-container text-break">
          {{ message.content|markdownify }}
        </div>
      {% endfor %}
    </div>
  </div>
  <form id="messageSendForm" class="list-group-item p-0">
    <div class="input-group">
      {{ form.content }}
      <button type="submit"
              class="btn btn-primary rounded-top-0"
              id="messageSendBtn">
        <i class="fa-solid fa-paper-plane mx-2"></i>
      </button>
    </div>
  </form>
{% endblock list_group %}

socnet/templates/messenger/chats.html
{% extends "list_group.html" %}

{% load i18n static %}

{% block title %}
  {% translate "Chats" %}
{% endblock title %}
{% block css %}
  {% if chats %}
    <link rel="stylesheet" href="{% static 'css/avatar_thumbnail.css' %}" />
  {% endif %}
{% endblock css %}
{% block javascript %}
  {% if chats %}
    <script type="module" src="{% static 'js/date_formatter.js' %}"></script>
    <script type="module" src="{% static 'js/autosize.js' %}"></script>
  {% endif %}
{% endblock javascript %}
{% block list_group %}
  {% if chats %}
    <form class="list-group-item p-0">
      <div class="input-group">
        {{ form.q }}
        <button type="submit" class="btn btn-primary rounded-bottom-0">
          <i class="fa-solid fa-magnifying-glass mx-2"></i>
        </button>
      </div>
    </form>
    {% for chat in chats %}
      <a href="{% url 'messenger:chat' chat.username %}"
         class="d-flex align-items-center list-group-item list-group-item-action">
        <div class="avatar-thumbnail d-flex align-items-center justify-content-center me-2">
          {% if chat.image %}
            <img src="{{ chat.image.url }}" loading="lazy" class="rounded" />
          {% else %}
            <i class="fa-solid fa-user text-secondary"></i>
          {% endif %}
        </div>
        <div class="text-break">
          <span class="text-body">{{ chat.display_name }}</span>
          <span class="ms-1 text-secondary">@{{ chat.username }}</span>
          <div class="text-secondary">{{ chat.last_message_truncated_content }}</div>
        </div>
        <div class="ms-auto text-secondary"
             data-epoch="{{ chat.last_message_date_epoch }}"></div>
      </a>
    {% endfor %}
  {% else %}
    <div class="list-group-item text-center">
      {% translate "You have no chats." %}
    </div>
  {% endif %}
{% endblock list_group %}

socnet/templates/messenger/messages_search.html
{% extends "list_group.html" %}

{% load i18n static %}

{% block title %}
  {% blocktranslate context "noun" %}Search messages{% endblocktranslate %}
{% endblock title %}
{% block css %}
  {% if messages_ %}
    <link rel="stylesheet" href="{% static 'css/avatar_thumbnail.css' %}" />
  {% endif %}
{% endblock css %}
{% block javascript %}
  {% if messages_ %}
    <script type="module" src="{% static 'js/date_formatter.js' %}"></script>
  {% endif %}
  <script type="module" src="{% static 'js/autosize.js' %}"></script>
{% endblock javascript %}
{% block list_group %}
  <form class="list-group-item p-0">
    <div class="input-group">
      {{ form.q }}
      <button type="submit" class="btn btn-primary rounded-bottom-0">
        <i class="fa-solid fa-magnifying-glass mx-2"></i>
      </button>
    </div>
  </form>
  {% for message, interlocutor in messages_ %}
    <a href="{% url 'messenger:chat' interlocutor.username %}#msg{{ message.pk }}"
       class="d-flex align-items-center list-group-item list-group-item-action">
      <div class="avatar-thumbnail d-flex align-items-center justify-content-center me-2">
        {% if interlocutor.image %}
          <img src="{{ interlocutor.image.url }}" loading="lazy" class="rounded" />
        {% else %}
          <i class="fa-solid fa-user text-secondary"></i>
        {% endif %}
      </div>
      <div class="text-break">
        <span class="text-body">{{ interlocutor.display_name }}</span>
        <span class="text-secondary">@{{ interlocutor.username }}</span>
        {% if message.sender == interlocutor %}
          <div class="text-secondary">{{ message.truncated_content }}</div>
        {% else %}
          <div class="d-flex align-items-center">
            <span class="avatar-thumbnail-font-size d-flex align-items-center justify-content-center me-2">
              {% if message.sender.image %}
                <img src="{{ message.sender.image.url }}" loading="lazy" class="rounded" />
              {% else %}
                <i class="fa-solid fa-user text-secondary"></i>
              {% endif %}
            </span>
            <span class="text-secondary">{{ message.truncated_content }}</span>
          </div>
        {% endif %}
      </div>
      <div class="ms-auto text-secondary"
           data-epoch="{{ message.date_created_epoch }}"></div>
    </a>
  {% empty %}
    <div class="list-group-item text-center">
      {% translate "No messages found." %}
    </div>
  {% endfor %}
{% endblock list_group %}